# Generated by Django 3.1.7 on 2021-02-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grapesjs', '0002_auto_20210227_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_content',
            name='css',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user_content',
            name='html',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='user_content',
            name='configuration',
            field=models.TextField(default=''),
        ),
    ]
