# Generated by Django 3.1.7 on 2021-02-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grapesjs', '0003_auto_20210227_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_content',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
